require("user.launch")
require("user.options")
require("user.icons")
require("user.keymaps")
spec("user.catppuccin")
spec("user.tokyo-night")
spec("user.one-dark")
spec("user.whichkey")
spec("user.treesitter")
spec("user.neotree")
spec("user.devicons")
spec("user.comment")
spec("user.telescope")
spec("user.autopairs")
spec("user.harpoon")
spec("user.surround")
spec("user.autotag")
spec("user.indentline")
spec("user.schemastore")
spec("user.noice")
spec("user.undotree")
spec("user.mason")
spec("user.lualine")
spec("user.lspconfig")
spec("user.cmp")
spec("user.null-ls")
spec("user.tmux-navigator")
spec("user.dressing")
spec("user.neoscroll")
spec("user.illuminate")
spec("user.oil")
spec("user.ufo")
spec("user.neotab")
spec("user.toogleterm")
spec("user.fidget")
spec("user.bqf")
spec("user.modicator")
spec("user.highlight-yank")
spec("user.easy-php")
-- spec("user.luasnip")
-- require("luasnip")
-- spec("user.php-enhanced")
-- require("user.luasnip")
-- spec("user.autocmds")
-- spec("user.gitsigns.lua")
-- spec("user.neogit.lua")
require("user.lazy")
