return {
	"ta-tikoma/php.easy.nvim",
	config = true,
	keys = {
		{ "<leader>db", "<CMD>PHPEasyDocBlock<CR>" },
		-- { "-r", "<CMD>PHPEasyReplica<CR>" },
		-- { "-c", "<CMD>PHPEasyCopy<CR>" },
		-- { "-d", "<CMD>PHPEasyDelete<CR>" },
		{ "<leader>ii", "<CMD>PHPEasyInitInterface<CR>" },
		{ "<leader>ic", "<CMD>PHPEasyInitClass<CR>" },
		{ "<leader>iac", "<CMD>PHPEasyInitAbstractClass<CR>" },
		{ "<leader>it", "<CMD>PHPEasyInitTrait<CR>" },
		-- { "-ie", "<CMD>PHPEasyInitEnum<CR>" },
		-- { "-ic", "<CMD>PHPEasyAppendConstruct<CR>" },
		-- { "-ac", "<CMD>PHPEasyAppendConstant<CR>" },
		-- { "-ap", "<CMD>PHPEasyAppendProperty<CR>" },
		-- { "-am", "<CMD>PHPEasyAppendMethod<CR>" },
		-- { "-aa", "<CMD>PHPEasyAppendArgument<CR>" },
	},
}
